# Generated by Django 4.1.7 on 2023-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appinmob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmuebble', models.CharField(max_length=100)),
                ('ambientes', models.IntegerField()),
                ('contrato', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(default='', max_length=140)),
                ('propietario', models.CharField(max_length=100)),
                ('m2', models.IntegerField()),
                ('estado', models.TextField(default='')),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='media/propiedades')),
                ('empleadoencargado', models.CharField(default='', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
