# Generated by Django 4.1.7 on 2023-04-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appinmob', '0002_propiedades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleados',
        ),
    ]
