# Generated by Django 4.1.7 on 2023-04-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appinmob', '0003_delete_empleados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedades',
            old_name='inmuebble',
            new_name='inmueble',
        ),
    ]
